kind: DaemonSet
apiVersion: apps/v1
metadata:
  labels:
      app: pan-fw
  name: pan-fw
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: pan-fw
  template:
    metadata:
      labels:
        app: pan-fw
      # Application Pods and Namespaces with annotation
      #     paloaltonetworks.com/firewall: pan-fw*
      # will be secured when there is a pan-fw daemonset running with exact same
      # annotation on the node
      annotations:
          paloaltonetworks.com/firewall: pan-fw
          paloaltonetworks.com/app: pan-fw
    spec:
      serviceAccountName: pan-fw
      priorityClassName: system-cluster-critical
      # Minimize downtime during a rolling upgrade or deletion; Can tell Kubernetes
      # to do a "force deletion": 
      # https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods
      # but for now allowing 10 seconds to do graceful removal of the slots by 
      # sending dereg to PAN-MGMT
      terminationGracePeriodSeconds: 10
      hostAliases:
      - ip: "169.254.202.1"
        hostnames:
          - "mgmt"
      #nodeSelector:  
      #  firewall: pan-fw
      containers:
        - name: pan-fw-container
          image: gcr.io/paloaltonetworks-public/cn-series-marketplace:ngfw-30
          command: ["/sbin/pan_pause"]
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash","-c","/sbin/pan_command pan_shutdown"]
          readinessProbe:
            exec:
              command: ["/sbin/pan_ready_check"]
            initialDelaySeconds: 15
            periodSeconds: 2
            failureThreshold: 1
            successThreshold: 2
          livenessProbe:
            exec:
              command: ["/sbin/pan_alive_check"]
            initialDelaySeconds: 60
            periodSeconds: 5
            # liveness is still the indicator of the container's health.
            failureThreshold: 600 #covers image download and panos start
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["ALL"]
          resources:
            requests:
              # configurable based on desired throughput, number of running pods
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 1
              memory: 2.25Gi
          volumeMounts:
          - mountPath: /opt/appinfo
            name: appinfo
          - mountPath: /dev/net/tun
            name: devnettun
            readOnly: false
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /etc/pan-fw-sw
            name: sw-secret
          envFrom:
          - configMapRef:
              name: pan-fw-config
          env:
            - name: CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: pan-fw-container
                  resource: requests.cpu
            - name: CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: pan-fw-container
                  resource: limits.cpu
            - name: MEMORY_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: pan-fw-container
                  resource: requests.memory
            - name: MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: pan-fw-container
                  resource: limits.memory
            - name: MY_POD_UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      volumes:
      - name: devnettun
        hostPath:
          path: /dev/net/tun
      - name: dshm
        emptyDir:
          medium: Memory
      - name: appinfo
        hostPath:
          # app pod info's directory location on host
          # below path should match pan-cni's "appinfo" volume and 
          # "appinfo_dir" configmap and pan-fw's part of "pan-cni-ready" volume
          path: /var/log/pan-appinfo
          type: Directory
      - name: pan-cni-ready
        hostPath:
          # block pan-fw pod scheduling till PAN CNI plugin insertion on the node
          path: /var/log/pan-appinfo/pan-cni-ready
          type: Directory
      - name: sw-secret
        secret:
          secretName: pan-fw-sw
