apiVersion: v1
kind: ConfigMap
metadata:
  name: pan-fw-config
  namespace: $namespace
data:
  PAN_SERVICE_NAME: "pan-mgmt"  # should match the pan-mgmt's Service name
  FAILOVER_MODE: "failopen"     # licensing failure behavior
  DP_RINGBUFFER: "60000"        # buffer count for memory/performance control
  #IPSEC_NAT_PORT_RANGE: "4500-4500"
