apiVersion: v1
kind: ConfigMap
metadata:
  name: pan-mgmt-config
  namespace: $namespace
data:
  PAN_OPERATION_MODE: "daemonset"
  PAN_SERVICE_NAME: "pan-mgmt"
  # Panorama settings
  PAN_PANORAMA_IP: "$panoramaIPAddress"
  PAN_PANORAMA_AUTH_KEY: "$panoramaAuthCode"
  PAN_DEVICE_GROUP: "$panoramaDevGroup"
  PAN_TEMPLATE: "$panoramaTemplate"
#Non-mandatory parameters
  #PAN_PANORAMA_CGNAME: ""
  #PAN_CERTIFICATE: ""
  #PAN_CERTKEYFILE: ""
  #PAN_CERTPASSPHRASE: ""
  #PAN_PANORAMA_IP2: ""
  #PAN_GTP_ENABLED: "true"
