apiVersion: v1
kind: ConfigMap
metadata:
  name: pan-mgmt-config
  namespace: $namespace
data:
  PAN_SERVICE_NAME: pan-mgmt-svc
  PAN_MGMT_SECRET: pan-mgmt-secret

  # Panorama settings
  PAN_PANORAMA_IP: "$panoramaIPAddress"
  PAN_DEVICE_GROUP: "$panoramaDevGroup"
  PAN_TEMPLATE: "$panoramaTemplate"
  PAN_PANORAMA_CGNAME: "$panoramaCGNAME"

  # Intended License Bundle type - "CN-X-BASIC, CN-X-BND1, CN-X-BND2"
  PAN_BUNDLE_TYPE: "CN-X-BND2"

#Non-mandatory parameters
  # Recommended to have same name as the cluster name provided in Panorama Kubernetes plugin - helps with easier identification of pods if managing multiple clusters with same Panorama
  #CLUSTER_NAME: "<Cluster name>"

  #PAN_PANORAMA_IP2: ""
  
  # Comment out to use CERTs otherwise bypass encrypted connection to etcd in pan-mgmt.
  #ETCD_CERT_BYPASS: ""          # No value needed

  # Comment out to use CERTs otherwise PSK for IPSec between pan-mgmt and pan-ngfw
  #IPSEC_CERT_BYPASS: ""         # No values needed
